### ISSUE TITLE
Déploiement en tests sans bmauthtoken

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-api#16]
Permettre de déployer en test sans le lien vers le changelog pour éviter de tirer des modifs qui ne passeront plus ensuite sur la prod.

Assurer que sans token on peut continuer à se loger

=>documenter la méthodo (manuelle) sur deploiement applicatif

**Comment by InakiUrrutia** [comment]
Le serveur de test ne viens plus chercher dans le changelog normalement, grace a un booleen crée dans application.properties .
C'est aussi mis a jour dans la doc interne de Mellisphera .

**Comment by lzpons** [comment]
soldé
